// AUTO-GENERATED by content_scaffold — do not edit.
declare module 'virtual:content' {
  export const pages: { "home": { "terminal": { "brand": string; "windowTitle": string; "prompt": string; "command": string; "greeting": string; "subheading": string; "status": string; "footer": string } } };
  export const home: { "terminal": { "brand": string; "windowTitle": string; "prompt": string; "command": string; "greeting": string; "subheading": string; "status": string; "footer": string } };
}
